version=0.1
[default.build.parameters]
beta_features = true
[default.sync.parameters]
beta_features = true

[default.deploy]
[default.deploy.parameters]
stack_name = "tod-leaderboard"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vbvsm4vrjhoa"
s3_prefix = "tod-leaderboard"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
