name: the-odd-dystrict
version: 1.0.0
description: The official plugin of The Odd Dystrict
author: 0xFlick
main: com.oddie.Oddie
api-version: 1.18
depend:
  - LuckPerms
softdepend:
  - Geyser-Spigot
commands:
  wallet:
    description: Connect your wallet to the Oddie metaverse
    usage: /<command>
  p2e:
    description: P2E Leaderboard commands
    usage: /<command> [action]
