name: the-odd-dystrict
version: 1.0.0
description: The official plugin of The Odd Dystrict
author: 0xFlick
main: com.oddie.Oddie
depend:
  - LuckPerms
commands:
  wallet:
    description: Connect your wallet to the Oddie metaverse
    usage: /<command>
    permission: oddie.command.wallet
